#
# GMT 6.6.0 Defaults file
#
# FONT Parameters
#
FONT_ANNOT_PRIMARY             = 11p,Helvetica,black
FONT_LABEL                     = 11p,Helvetica,black
#
# MAP Parameters
#
MAP_LABEL_OFFSET               = 6p
#
# PostScript Parameters
#
PS_CHAR_ENCODING               = Standard+
PS_MEDIA                       = a2
